site_name: boom-boom-81 archive
docs_dir: kb
site_dir: ../site
use_directory_urls: true

theme:
  name: material

plugins:
  - search
  - exclude-search:
      exclude:
        - roles/all.md
        - roles/by-author/*
        - records/*
        - records-completed/*